### ISSUE TITLE
Component Checklist

### ISSUE THREAD

**Issue by Harbs** [unhurdle/spectrum-royale#5]
- [ ] Accordion
- [ ] Action Button
- [ ] Action Menu
- [ ] Alert
- [ ] Asset List
- [ ] Avatar
- [ ] Banner
- [ ] Bar Loader
- [ ] Breadcrumbs
- [ ] Button
- [ ] Button Group
- [ ] Calendar
- [ ] Card
- [ ] Checkbox
- [ ] Circle Loader
- [ ] Clear Button
- [ ] Coach Mark
- [ ] ComboBox
- [ ] Cycle Button
- [ ] Date Picker
- [ ] Dial
- [ ] Dialog
- [ ] Drop Indicator
- [ ] Dropdown
- [ ] Dropzone
- [ ] Field Group
- [ ] Field Label
- [ ] Form
- [ ] Illustrated Message
- [ ] Label
- [ ] Link
- [ ] Logic Button
- [ ] Menu
- [ ] Miller Columns
- [ ] Page?
- [ ] Pagination
- [ ] Popover (+ Dialog Style)
- [ ] Quick Actions
- [ ] Radio
- [ ] Rating
- [ ] Rule
- [ ] Search
- [ ] Search Within
- [ ] SideNav
- [ ] SideNav Heading
- [ ] SideNav Multilevel
- [ ] Slider (with variants)
- [ ] Split Button
- [ ] Split View (Horizontal, Vertical)
- [ ] Status Light
- [ ] Steplist
- [ ] Stepper
- [ ] Switch
- [ ] Table (with variants)
- [ ] Tabs (with variants?)
- [ ] Tags
- [ ] TextArea
- [ ] Toast
- [ ] Tool
- [ ] ToolTip
- [ ] TreeView
- [ ] Typography
- [ ] Typography -- Article
- [ ] Typography -- Body
- [ ] Typography -- Code
- [ ] Typography -- Display
- [ ] Typography -- Han
- [ ] Typography -- Heading
- [ ] Well

**Comment by Harbs** [comment]
"Han" is nor needed. The language is specified in one of the Typography containers

**Comment by GarthDB** [comment]
@Harbs this is awesome!
